# Generated by Django 4.2.7 on 2023-11-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HorariosBloqueados",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("Horario", models.DateField()),
            ],
            options={
                "verbose_name_plural": "Horarios_Bloqueados",
            },
        ),
        migrations.CreateModel(
            name="Pacote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Pacotes",
            },
        ),
        migrations.CreateModel(
            name="Procedimentos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Procedimentos",
            },
        ),
    ]
